### ISSUE TITLE
More Chow tape plugins

### ISSUE THREAD

**Issue by schollz** [madskjeldgaard/portedplugins#33]
Hi @madskjeldgaard , I absolutely love this project. Its been an excellent part of my process and I've really enjoyed using this plugins as part of norns via SuperCollider.

I am working on porting more of Jatin's tape plugins (namely Loss, Degrade, and Chew). I've got them working and I'm wondering if you would be interest in a PR with these to this repo? If so I can tidy them up and make a PR.

**Comment by madskjeldgaard** [comment]
That would be much appreciated. Looking forward to the pull request! On 22 Jan 2023, at 00.58, Zack ***@***.***> wrote:﻿
Hi @madskjeldgaard , I absolutely love this project. Its been an excellent part of my process and I've really enjoyed using this plugins as part of norns via SuperCollider.
I am working on porting more of Jatin's tape plugins (namely Loss, Degrade, and Chew). I've got them working and I'm wondering if you would be interest in a PR with these to this repo? If so I can tidy them up and make a PR.

**Comment by schollz** [comment]
Great, will do!
