### ISSUE TITLE
Release 0.4.1 does not work on my Mac

### ISSUE THREAD

**Issue by geoffroymontel** [madskjeldgaard/portedplugins#36]
**Describe the bug**
With new release 0.4.1, I am getting the following error on my Mac when booting scsynth

*** ERROR: dlopen '/Users/geoffroy/Library/Application Support/SuperCollider/Extensions/PortedPlugins/VASEM12_scsynth.scx' err 'dlopen(/Users/geoffroy/Library/Application Support/SuperCollider/Extensions/PortedPlugins/VASEM12_scsynth.scx, 2): no suitable image found.  Did find:
	/Users/geoffroy/Library/Application Support/SuperCollider/Extensions/PortedPlugins/VASEM12_scsynth.scx: cannot load 'VASEM12_scsynth.scx' (load command 0x80000034 is unknown)
	/Users/geoffroy/Library/Application Support/SuperCollider/Extensions/PortedPlugins/VASEM12_scsynth.scx: cannot load 'VASEM12_scsynth.scx' (load command 0x80000034 is unknown)'

**To Reproduce**
1. download release 0.4.1 for Mac
2. unzip to SC Extensions folder
3. start SC
4. boot server

**Expected behavior**

I'd expect it to work as release 0.3.1

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Architecture: x86
 - SC Version: 3.13.0
 - PortedPlugins Version: 0.4.1

Thanks !

**Comment by vpavlenko** [comment]
I've made a build that works on my M1:

[PortedPlugins - 0.4.1 - Mac M1 arm64e.zip](https://github.com/madskjeldgaard/portedplugins/files/10887730/PortedPlugins.-.0.4.1.-.Mac.M1.arm64e.zip)

**Comment by madskjeldgaard** [comment]
Thanks for this! I don't have time to fix this at the moment, so I would recommend building from source if this is an issue until someone makes a PR for this. You can do that pretty easily using this plugin: 

https://github.com/madskjeldgaard/plugins.quark

**Comment by schmolmo** [comment]
Hey there! 

I just ran into the same issue and found a solution (I'm no cmake expert at all, so maybe use with caution?): Apparently you have to set the [CMAKE_OSX_DEPLOYMENT_TARGET](https://stackoverflow.com/questions/34208360/cmake-seems-to-ignore-cmake-osx-deployment-target) variable in CMakeLists.txt. I did that by adding this line after line 11 in CMakeLists.txt:

`set(CMAKE_OSX_DEPLOYMENT_TARGET "10.13" CACHE STRING "Minimum OS X deployment version")` 

With the "10.13" being your OS Version. After that, I re-ran the build instructions from the README and everything worked flawlessly.

Hope this helps!
